spring:
    data:
        mongodb:
            host: localhost
            port: 27117
            database: englishlearning
            username: englishlearningadmin
            password: password
google:
    api:
        key: AIzaSyA6yFgxn-ZedxCghH1X4xwuLLcltaUlK3c
translate:
    yandex:
        api:
            key: trnsl.1.1.20170201T133356Z.dd25c6f5b98a0167.896a4b589be6f69359187182616b7e2fe07963c6
tts:
    voicerss:
        api:
            key: 6a165eb655ea4e84bcbe4cff8082c463